// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://luyocboqhigwptwthzmn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx1eW9jYm9xaGlnd3B0d3Roem1uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4NTM0NjUsImV4cCI6MjA2ODQyOTQ2NX0.9Y4bBvfeGc0K-yL6OJVZNcvztj2OFThQa4fBz5wOayo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});